apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm-app-frontend
spec:
  selector:
    matchLabels:
      app: ecm-app-frontend
  template:
    metadata:
      labels:
        app: ecm-app-frontend
    spec:
      containers:
        - name: ecm-app-frontend
          image: IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '16Mi'
              cpu: '10m'
            limits:
              memory: '128Mi'
              cpu: '250m'
          securityContext:
            runAsUser: 1000
            privileged: false
            allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: acr-secret
---
kind: Service
apiVersion: v1
metadata:
  name: ecm-app-frontend
  labels:
    tier: frontend
spec:
  selector:
    app: ecm-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ecm-app-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecm-app-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
